// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Usar variáveis de ambiente com fallback para desenvolvimento
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xmjucbhmdnniqmvvvkwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtanVjYmhtZG5uaXFtdnZ2a3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTE3OTMsImV4cCI6MjA2NTY2Nzc5M30.biFxj6QTL76YE48p9qTjCzk2ZCZiu9579HQsea3TjPo";

// Validação das variáveis de ambiente
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Variáveis de ambiente do Supabase não configuradas corretamente');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);